# Generated by Django 5.1.2 on 2024-10-26 10:05

import apps.utils
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='имя')),
                ('location', models.TextField(verbose_name='адресс')),
                ('description', models.TextField(verbose_name='описание')),
                ('photo', models.ImageField(upload_to=apps.utils.custom_upload_path, verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Артист',
                'verbose_name_plural': 'Артисты',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=apps.utils.custom_upload_path, verbose_name='Фото')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Запись блога',
                'verbose_name_plural': 'Записи блога',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Названия события')),
                ('description', models.TextField(verbose_name='Описание события')),
                ('image', models.ImageField(upload_to=apps.utils.custom_upload_path, verbose_name='Фото')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время события')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'Событии',
            },
        ),
    ]
