# Generated by Django 5.1.2 on 2024-10-30 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_artist_blog_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя отправителя')),
                ('number', models.CharField(max_length=255, verbose_name='Номер телефона отправителя')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('subject', models.CharField(max_length=255, verbose_name='Тема отправителя')),
                ('message', models.TextField(verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Оставленный отзыв',
                'verbose_name_plural': 'Оставденные отзывы',
            },
        ),
    ]
